### ISSUE TITLE
Hello, I can not run this program, can u help me?

### ISSUE THREAD

**Issue by GaoZYun** [xiaosj/CT-DICOM-GUI#1]
error message:
/Users/macintosh/opt/anaconda3/bin/python3.8 /Users/macintosh/PycharmProjects/pythonProject/CT-DICOM-GUI-master/CT_gui.py
/Users/macintosh/PycharmProjects/pythonProject/CT-DICOM-GUI-master/CT_gui.py:13: MatplotlibDeprecationWarning: 
The is_pyqt5 function was deprecated in Matplotlib 3.3 and will be removed two minor releases later. Use QtCore.qVersion() instead.
  if is_pyqt5():
Traceback (most recent call last):
  File "/Users/macintosh/PycharmProjects/pythonProject/CT-DICOM-GUI-master/CT_gui.py", line 55, in <lambda>
    self.checkBox_center_lines.stateChanged.connect(lambda:self.display(True))
  File "/Users/macintosh/PycharmProjects/pythonProject/CT-DICOM-GUI-master/CT_gui.py", line 307, in display
    self.pxy.imshow(self.ct.voxel[z0,:,:], cmap='gray', aspect=self.ct.dy/self.ct.dx)
AttributeError: 'myApp' object has no attribute 'ct'

Please,Thx!!!

**Comment by GaoZYun** [comment]
I need some new functions, can you give me a contact information？

**Comment by xiaosj** [comment]
It happens when you try to use the scroll before opening DICOM files.  I may fix it later.  Thank you @GaoZYun for finding it.
